// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pokemonnxt/packets/communications.proto

package com.pokemonnxt.packets;

public final class Communications {
  private Communications() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LOGINOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string username = 1;
    boolean hasUsername();
    String getUsername();
    
    // required string password = 2;
    boolean hasPassword();
    String getPassword();
    
    // optional string email = 3;
    boolean hasEmail();
    String getEmail();
  }
  public static final class LOGIN extends
      com.google.protobuf.GeneratedMessage
      implements LOGINOrBuilder {
    // Use LOGIN.newBuilder() to construct.
    private LOGIN(Builder builder) {
      super(builder);
    }
    private LOGIN(boolean noInit) {}
    
    private static final LOGIN defaultInstance;
    public static LOGIN getDefaultInstance() {
      return defaultInstance;
    }
    
    public LOGIN getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string password = 2;
    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      username_ = "";
      password_ = "";
      email_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pokemonnxt.packets.Communications.LOGIN prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pokemonnxt.packets.Communications.LOGINOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_fieldAccessorTable;
      }
      
      // Construct using com.pokemonnxt.packets.Communications.LOGIN.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pokemonnxt.packets.Communications.LOGIN.getDescriptor();
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN getDefaultInstanceForType() {
        return com.pokemonnxt.packets.Communications.LOGIN.getDefaultInstance();
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN build() {
        com.pokemonnxt.packets.Communications.LOGIN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pokemonnxt.packets.Communications.LOGIN buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pokemonnxt.packets.Communications.LOGIN result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN buildPartial() {
        com.pokemonnxt.packets.Communications.LOGIN result = new com.pokemonnxt.packets.Communications.LOGIN(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pokemonnxt.packets.Communications.LOGIN) {
          return mergeFrom((com.pokemonnxt.packets.Communications.LOGIN)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pokemonnxt.packets.Communications.LOGIN other) {
        if (other == com.pokemonnxt.packets.Communications.LOGIN.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string username = 1;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
      }
      
      // required string password = 2;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
      }
      
      // optional string email = 3;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:packets.LOGIN)
    }
    
    static {
      defaultInstance = new LOGIN(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:packets.LOGIN)
  }
  
  public interface LOGIN_SUCCESSOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 GTID = 1;
    boolean hasGTID();
    int getGTID();
    
    // required bool new = 2;
    boolean hasNew();
    boolean getNew();
    
    // required .packets.TYPE_LOCATION spawn = 3;
    boolean hasSpawn();
    com.pokemonnxt.packets.Communications.TYPE_LOCATION getSpawn();
    com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder getSpawnOrBuilder();
  }
  public static final class LOGIN_SUCCESS extends
      com.google.protobuf.GeneratedMessage
      implements LOGIN_SUCCESSOrBuilder {
    // Use LOGIN_SUCCESS.newBuilder() to construct.
    private LOGIN_SUCCESS(Builder builder) {
      super(builder);
    }
    private LOGIN_SUCCESS(boolean noInit) {}
    
    private static final LOGIN_SUCCESS defaultInstance;
    public static LOGIN_SUCCESS getDefaultInstance() {
      return defaultInstance;
    }
    
    public LOGIN_SUCCESS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_SUCCESS_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_SUCCESS_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 GTID = 1;
    public static final int GTID_FIELD_NUMBER = 1;
    private int gTID_;
    public boolean hasGTID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGTID() {
      return gTID_;
    }
    
    // required bool new = 2;
    public static final int NEW_FIELD_NUMBER = 2;
    private boolean new_;
    public boolean hasNew() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getNew() {
      return new_;
    }
    
    // required .packets.TYPE_LOCATION spawn = 3;
    public static final int SPAWN_FIELD_NUMBER = 3;
    private com.pokemonnxt.packets.Communications.TYPE_LOCATION spawn_;
    public boolean hasSpawn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.pokemonnxt.packets.Communications.TYPE_LOCATION getSpawn() {
      return spawn_;
    }
    public com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder getSpawnOrBuilder() {
      return spawn_;
    }
    
    private void initFields() {
      gTID_ = 0;
      new_ = false;
      spawn_ = com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasGTID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNew()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpawn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSpawn().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, gTID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, new_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, spawn_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, gTID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, new_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, spawn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.LOGIN_SUCCESS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pokemonnxt.packets.Communications.LOGIN_SUCCESS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pokemonnxt.packets.Communications.LOGIN_SUCCESSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_SUCCESS_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_LOGIN_SUCCESS_fieldAccessorTable;
      }
      
      // Construct using com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSpawnFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        gTID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        new_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (spawnBuilder_ == null) {
          spawn_ = com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance();
        } else {
          spawnBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.getDescriptor();
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN_SUCCESS getDefaultInstanceForType() {
        return com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.getDefaultInstance();
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN_SUCCESS build() {
        com.pokemonnxt.packets.Communications.LOGIN_SUCCESS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pokemonnxt.packets.Communications.LOGIN_SUCCESS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pokemonnxt.packets.Communications.LOGIN_SUCCESS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pokemonnxt.packets.Communications.LOGIN_SUCCESS buildPartial() {
        com.pokemonnxt.packets.Communications.LOGIN_SUCCESS result = new com.pokemonnxt.packets.Communications.LOGIN_SUCCESS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gTID_ = gTID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.new_ = new_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (spawnBuilder_ == null) {
          result.spawn_ = spawn_;
        } else {
          result.spawn_ = spawnBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pokemonnxt.packets.Communications.LOGIN_SUCCESS) {
          return mergeFrom((com.pokemonnxt.packets.Communications.LOGIN_SUCCESS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pokemonnxt.packets.Communications.LOGIN_SUCCESS other) {
        if (other == com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.getDefaultInstance()) return this;
        if (other.hasGTID()) {
          setGTID(other.getGTID());
        }
        if (other.hasNew()) {
          setNew(other.getNew());
        }
        if (other.hasSpawn()) {
          mergeSpawn(other.getSpawn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasGTID()) {
          
          return false;
        }
        if (!hasNew()) {
          
          return false;
        }
        if (!hasSpawn()) {
          
          return false;
        }
        if (!getSpawn().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gTID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              new_ = input.readBool();
              break;
            }
            case 26: {
              com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder subBuilder = com.pokemonnxt.packets.Communications.TYPE_LOCATION.newBuilder();
              if (hasSpawn()) {
                subBuilder.mergeFrom(getSpawn());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSpawn(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 GTID = 1;
      private int gTID_ ;
      public boolean hasGTID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getGTID() {
        return gTID_;
      }
      public Builder setGTID(int value) {
        bitField0_ |= 0x00000001;
        gTID_ = value;
        onChanged();
        return this;
      }
      public Builder clearGTID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gTID_ = 0;
        onChanged();
        return this;
      }
      
      // required bool new = 2;
      private boolean new_ ;
      public boolean hasNew() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getNew() {
        return new_;
      }
      public Builder setNew(boolean value) {
        bitField0_ |= 0x00000002;
        new_ = value;
        onChanged();
        return this;
      }
      public Builder clearNew() {
        bitField0_ = (bitField0_ & ~0x00000002);
        new_ = false;
        onChanged();
        return this;
      }
      
      // required .packets.TYPE_LOCATION spawn = 3;
      private com.pokemonnxt.packets.Communications.TYPE_LOCATION spawn_ = com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.pokemonnxt.packets.Communications.TYPE_LOCATION, com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder, com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder> spawnBuilder_;
      public boolean hasSpawn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.pokemonnxt.packets.Communications.TYPE_LOCATION getSpawn() {
        if (spawnBuilder_ == null) {
          return spawn_;
        } else {
          return spawnBuilder_.getMessage();
        }
      }
      public Builder setSpawn(com.pokemonnxt.packets.Communications.TYPE_LOCATION value) {
        if (spawnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          spawn_ = value;
          onChanged();
        } else {
          spawnBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setSpawn(
          com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder builderForValue) {
        if (spawnBuilder_ == null) {
          spawn_ = builderForValue.build();
          onChanged();
        } else {
          spawnBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeSpawn(com.pokemonnxt.packets.Communications.TYPE_LOCATION value) {
        if (spawnBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              spawn_ != com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance()) {
            spawn_ =
              com.pokemonnxt.packets.Communications.TYPE_LOCATION.newBuilder(spawn_).mergeFrom(value).buildPartial();
          } else {
            spawn_ = value;
          }
          onChanged();
        } else {
          spawnBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearSpawn() {
        if (spawnBuilder_ == null) {
          spawn_ = com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance();
          onChanged();
        } else {
          spawnBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder getSpawnBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSpawnFieldBuilder().getBuilder();
      }
      public com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder getSpawnOrBuilder() {
        if (spawnBuilder_ != null) {
          return spawnBuilder_.getMessageOrBuilder();
        } else {
          return spawn_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.pokemonnxt.packets.Communications.TYPE_LOCATION, com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder, com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder> 
          getSpawnFieldBuilder() {
        if (spawnBuilder_ == null) {
          spawnBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pokemonnxt.packets.Communications.TYPE_LOCATION, com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder, com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder>(
                  spawn_,
                  getParentForChildren(),
                  isClean());
          spawn_ = null;
        }
        return spawnBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:packets.LOGIN_SUCCESS)
    }
    
    static {
      defaultInstance = new LOGIN_SUCCESS(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:packets.LOGIN_SUCCESS)
  }
  
  public interface TYPE_LOCATIONOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 X = 1;
    boolean hasX();
    int getX();
    
    // required int32 Y = 2;
    boolean hasY();
    int getY();
    
    // required int32 Z = 3;
    boolean hasZ();
    int getZ();
    
    // required int32 Pitch = 4;
    boolean hasPitch();
    int getPitch();
    
    // required int32 Yaw = 5;
    boolean hasYaw();
    int getYaw();
    
    // required int32 Roll = 6;
    boolean hasRoll();
    int getRoll();
  }
  public static final class TYPE_LOCATION extends
      com.google.protobuf.GeneratedMessage
      implements TYPE_LOCATIONOrBuilder {
    // Use TYPE_LOCATION.newBuilder() to construct.
    private TYPE_LOCATION(Builder builder) {
      super(builder);
    }
    private TYPE_LOCATION(boolean noInit) {}
    
    private static final TYPE_LOCATION defaultInstance;
    public static TYPE_LOCATION getDefaultInstance() {
      return defaultInstance;
    }
    
    public TYPE_LOCATION getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_TYPE_LOCATION_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pokemonnxt.packets.Communications.internal_static_packets_TYPE_LOCATION_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 X = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // required int32 Y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    // required int32 Z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private int z_;
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getZ() {
      return z_;
    }
    
    // required int32 Pitch = 4;
    public static final int PITCH_FIELD_NUMBER = 4;
    private int pitch_;
    public boolean hasPitch() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPitch() {
      return pitch_;
    }
    
    // required int32 Yaw = 5;
    public static final int YAW_FIELD_NUMBER = 5;
    private int yaw_;
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getYaw() {
      return yaw_;
    }
    
    // required int32 Roll = 6;
    public static final int ROLL_FIELD_NUMBER = 6;
    private int roll_;
    public boolean hasRoll() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getRoll() {
      return roll_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
      z_ = 0;
      pitch_ = 0;
      yaw_ = 0;
      roll_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPitch()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYaw()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoll()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pitch_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, yaw_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, roll_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pitch_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, yaw_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, roll_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pokemonnxt.packets.Communications.TYPE_LOCATION parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pokemonnxt.packets.Communications.TYPE_LOCATION prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pokemonnxt.packets.Communications.TYPE_LOCATIONOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_TYPE_LOCATION_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pokemonnxt.packets.Communications.internal_static_packets_TYPE_LOCATION_fieldAccessorTable;
      }
      
      // Construct using com.pokemonnxt.packets.Communications.TYPE_LOCATION.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        pitch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        yaw_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        roll_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDescriptor();
      }
      
      public com.pokemonnxt.packets.Communications.TYPE_LOCATION getDefaultInstanceForType() {
        return com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance();
      }
      
      public com.pokemonnxt.packets.Communications.TYPE_LOCATION build() {
        com.pokemonnxt.packets.Communications.TYPE_LOCATION result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pokemonnxt.packets.Communications.TYPE_LOCATION buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pokemonnxt.packets.Communications.TYPE_LOCATION result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pokemonnxt.packets.Communications.TYPE_LOCATION buildPartial() {
        com.pokemonnxt.packets.Communications.TYPE_LOCATION result = new com.pokemonnxt.packets.Communications.TYPE_LOCATION(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pitch_ = pitch_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.yaw_ = yaw_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.roll_ = roll_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pokemonnxt.packets.Communications.TYPE_LOCATION) {
          return mergeFrom((com.pokemonnxt.packets.Communications.TYPE_LOCATION)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pokemonnxt.packets.Communications.TYPE_LOCATION other) {
        if (other == com.pokemonnxt.packets.Communications.TYPE_LOCATION.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasPitch()) {
          setPitch(other.getPitch());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        if (other.hasRoll()) {
          setRoll(other.getRoll());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        if (!hasPitch()) {
          
          return false;
        }
        if (!hasYaw()) {
          
          return false;
        }
        if (!hasRoll()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              z_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pitch_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              yaw_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              roll_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 X = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Z = 3;
      private int z_ ;
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getZ() {
        return z_;
      }
      public Builder setZ(int value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Pitch = 4;
      private int pitch_ ;
      public boolean hasPitch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPitch() {
        return pitch_;
      }
      public Builder setPitch(int value) {
        bitField0_ |= 0x00000008;
        pitch_ = value;
        onChanged();
        return this;
      }
      public Builder clearPitch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pitch_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Yaw = 5;
      private int yaw_ ;
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getYaw() {
        return yaw_;
      }
      public Builder setYaw(int value) {
        bitField0_ |= 0x00000010;
        yaw_ = value;
        onChanged();
        return this;
      }
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yaw_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 Roll = 6;
      private int roll_ ;
      public boolean hasRoll() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getRoll() {
        return roll_;
      }
      public Builder setRoll(int value) {
        bitField0_ |= 0x00000020;
        roll_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoll() {
        bitField0_ = (bitField0_ & ~0x00000020);
        roll_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:packets.TYPE_LOCATION)
    }
    
    static {
      defaultInstance = new TYPE_LOCATION(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:packets.TYPE_LOCATION)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packets_LOGIN_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packets_LOGIN_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packets_LOGIN_SUCCESS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packets_LOGIN_SUCCESS_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_packets_TYPE_LOCATION_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_packets_TYPE_LOCATION_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+com/pokemonnxt/packets/communications." +
      "proto\022\007packets\":\n\005LOGIN\022\020\n\010username\030\001 \002(" +
      "\t\022\020\n\010password\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\"Q\n\rLO" +
      "GIN_SUCCESS\022\014\n\004GTID\030\001 \002(\005\022\013\n\003new\030\002 \002(\010\022%" +
      "\n\005spawn\030\003 \002(\0132\026.packets.TYPE_LOCATION\"Z\n" +
      "\rTYPE_LOCATION\022\t\n\001X\030\001 \002(\005\022\t\n\001Y\030\002 \002(\005\022\t\n\001" +
      "Z\030\003 \002(\005\022\r\n\005Pitch\030\004 \002(\005\022\013\n\003Yaw\030\005 \002(\005\022\014\n\004R" +
      "oll\030\006 \002(\005B(\n\026com.pokemonnxt.packetsB\016Com" +
      "munications"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_packets_LOGIN_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_packets_LOGIN_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packets_LOGIN_descriptor,
              new java.lang.String[] { "Username", "Password", "Email", },
              com.pokemonnxt.packets.Communications.LOGIN.class,
              com.pokemonnxt.packets.Communications.LOGIN.Builder.class);
          internal_static_packets_LOGIN_SUCCESS_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_packets_LOGIN_SUCCESS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packets_LOGIN_SUCCESS_descriptor,
              new java.lang.String[] { "GTID", "New", "Spawn", },
              com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.class,
              com.pokemonnxt.packets.Communications.LOGIN_SUCCESS.Builder.class);
          internal_static_packets_TYPE_LOCATION_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_packets_TYPE_LOCATION_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_packets_TYPE_LOCATION_descriptor,
              new java.lang.String[] { "X", "Y", "Z", "Pitch", "Yaw", "Roll", },
              com.pokemonnxt.packets.Communications.TYPE_LOCATION.class,
              com.pokemonnxt.packets.Communications.TYPE_LOCATION.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
